version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: Dockerfile
    image: divisora_core-manager
    container_name: divisora_core-manager_web
    ports:
      - 5000:5000
    networks:
      - frontend
      - celery_backend    
    depends_on:
      - redis

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: divisora_core-manager_redis
    networks:
      celery_backend:
        aliases:
          - redis

  celery_worker:
    image: divisora_core-manager
    container_name: divisora_core-manager_worker
    command: "celery -A run worker --loglevel INFO"
    networks:
      - celery_backend    
    depends_on:
      - redis

  celery_beat:
    image: divisora_core-manager
    container_name: divisora_core-manager_beat
    command: "celery -A run beat --loglevel INFO"
    networks:
      - celery_backend    
    depends_on:
      - redis

networks:
  frontend:
    driver: bridge
  celery_backend:
    driver: bridge